language: python
python:
  - "2.7"
#  - "3.4"
# command to install dependencies\
cache: pip
install:
  - sudo apt-get install -qq python-scipy python-numpy libatlas-dev libatlas3gf-base libblas-dev liblapack-dev python-matplotlib python-pandas
  #- deactivate
  # Create a new virtualenv using system site packages for numpy and scipy
  - virtualenv --system-site-packages testvenv
  - source testvenv/bin/activate
  - pip install pip --upgrade
  - pip install coverage python-coveralls
  - pip install nose scikit-learn --upgrade
  - python setup.py build install
# command to run tests
script: nosetests  --with-coverage --cover-package=pyriemann
after_success:
  - deactivate
  - sudo pip install python-coveralls --upgrade
  - coveralls